### ISSUE TITLE
Error when upgrading to version 2.3.0

### ISSUE THREAD

**Issue by carlos-hernandez** [craigburke/bower-installer-gradle#6]
After upgrading to version 2.3.0 of the plugin I got this error in my build:

```console
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'web-client'.
> Task with name 'run' not found in root project 'web-client'

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'web-client'.
Caused by: org.gradle.api.UnknownTaskException: Task with name 'run' not found in root project 'web-client'.
        at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:80)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:210)
        at org.gradle.api.internal.tasks.DefaultTaskCollection.getByName(DefaultTaskCollection.java:31)
        at org.gradle.api.tasks.TaskCollection$getByName.call(Unknown Source)
        at com.craigburke.gradle.BowerInstallerPlugin$_apply_closure6_closure15.doCall(BowerInstallerPlugin.groovy:102)
        at com.craigburke.gradle.BowerInstallerPlugin$_apply_closure6.doCall(BowerInstallerPlugin.groovy:101)

```

According to the stacktrace, this lines at the end of the **BowerInstallerPlugin.groovy** might be causing this error:
```groovy
project.afterEvaluate {
    ['run', 'bootRun', 'assetCompile'].each { String taskName ->
        def buildTask = project.tasks.getByName(taskName)
        if (buildTask) {
            buildTask.dependsOn 'bowerInstall'
        }
    }
}
```

The only change in **build.gradle** is this:
```gradle
plugins {
    id 'com.craigburke.bower-installer' version '2.3.0'
}
```

The tasks 'run', 'bootRun', 'assetCompile' are not present when executing **gradle tasks --all**.

**Comment by craigburke** [comment]
@carlos-hernandez you're exactly right. I should have used `findByName` instead of `getByName` there. Give version 2.3.1 a shot.

**Comment by carlos-hernandez** [comment]
Yes, that solved the problem. Thanks.

**Comment by craigburke** [comment]
:+1:
