### ISSUE TITLE
node_modules folder missing

### ISSUE THREAD

**Issue by Schlogen** [craigburke/bower-installer-gradle#8]
Attempting to install with the following config results in the following error. Grails 3.1 SNAPSHOT and Windows.

```
bower {
    'angular'('1.4.x') {
        source 'angular.js'
    }
}
```

```
module.js:333
    throw err;
          ^
Error: Cannot find module 'C:\Users\jjkleeh\IdeaProjects\abc\node_modules\bower-installer\node_modules\bower\bin\bower'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Function.Module.runMain (module.js:490:10)
    at startup (node.js:123:16)
    at node.js:1031:3
:bowerComponents FAILED
```

**Comment by Schlogen** [comment]
Repo that reproduces the error

https://github.com/Schlogen/bower_gradle_test

**Comment by craigburke** [comment]
I think we resolved this a while ago. Reopen if I'm wrong.
